const sampleData = {
  products: [
    {
      name: "Yamaha F310",
      slug: "yamaha-f310",
      category: "Acoustic Guitar",
      images: ["/images/yamaha-f310.jpg"],
      brand: "Yamaha",
      description: "Acoustic guitar",
      stock: 10,
      price: 299.99,
    },
    {
      name: "Fender Stratocaster",
      slug: "fender-stratocaster",
      category: "Electric Guitar",
      images: ["/images/fender-stratocaster.jpg"],
      brand: "Fender",
      description: "Electric guitar",
      stock: 5,
      price: 899.99,
    },
    {
      name: "Gibson Les Paul",
      slug: "gibson-les-paul",
      category: "Electric Guitar",
      images: ["/images/gibson-les-paul.jpg"],
      brand: "Gibson",
      description: "Electric guitar",
      stock: 3,
      price: 1999.99,
    },
    {
      name: "Ibanez RG",
      slug: "ibanez-rg",
      category: "Electric Guitar",
      images: ["/images/ibanez-rg.jpg"],
      brand: "Ibanez",
      description: "Electric guitar",
      stock: 8,
      price: 599.99,
    },
    {
      name: "Martin D-28",
      slug: "martin-d28",
      category: "Acoustic Guitar",
      images: ["/images/martin-d28.jpg"],
      brand: "Martin",
      description: "Acoustic guitar",
      stock: 2,
      price: 2999.99,
    },
    {
      name: "Taylor 214ce",
      slug: "taylor-214ce",
      category: "Acoustic Guitar",
      images: ["/images/taylor-214ce.jpg"],
      brand: "Taylor",
      description: "Acoustic guitar",
      stock: 4,
      price: 1299.99,
    },
    {
      name: "Epiphone Les Paul",
      slug: "epiphone-les-paul",
      category: "Electric Guitar",
      images: ["/images/epiphone-les-paul.jpg"],
      brand: "Epiphone",
      description: "Electric guitar",
      stock: 12,
      price: 399.99,
    },
    {
      name: "PRS SE Custom 24",
      slug: "prs-se-custom24",
      category: "Electric Guitar",
      images: ["/images/prs-se-custom24.jpg"],
      brand: "PRS",
      description: "Electric guitar",
      stock: 6,
      price: 799.99,
    },
    {
      name: "Gretsch G2622",
      slug: "gretsch-g2622",
      category: "Electric Guitar",
      images: ["/images/gretsch-g2622.jpg"],
      brand: "Gretsch",
      description: "Electric guitar",
      stock: 7,
      price: 549.99,
    },
    {
      name: "Squier Bullet",
      slug: "squier-bullet",
      category: "Electric Guitar",
      images: ["/images/squier-bullet.jpg"],
      brand: "Squier",
      description: "Electric guitar",
      stock: 15,
      price: 199.99,
    },
  ],
};
export default sampleData;
